n = input ('Digite Algo: ')
print('O tipo primitivo desse valor é: {}'.format(type(n)))
print('Só tem espaços? {}'.format(n.isspace()))
print('É um numero? {}'.format(n.isnumeric()))
print('É alfabetico? {}'.format(n.isalpha()))
print('É alfanumerico? {}'.format(n.isalnum()))
print('Esta em Maiusculas? {}'.format(n.isupper()))
print('Esta em minusculas? {}'.format(n.islower()))
print('Esta capitalizada? {}'.format(n.istitle()))