print('='*18)
print('| ESCOLA GALDINO |')
print('='*18)
print('Vamos calcular a media do aluno!')
n1 = float(input('Insira a primeira nota: '))
n2 = float(input('Insira a segunda nota: '))
print('A media do Aluno é {:.1f}'.format((n1+n2)/2))